### ISSUE TITLE
missing hunts/battles/ any other command

### ISSUE THREAD

**Issue by 420002** [Mid0aria/owofarmbot#44]
sometimes the bot will send commands to early and they won't register by a second or a few. not sure if its something on my end or instructions on how to fix would be appreciated, thanks.

**Comment by Mid0aria** [comment]
fixed https://github.com/Mid0aria/owofarmbot/commit/f7d22a48ac97a20f5e62881753282ad623fdf950

**Comment by 420002** [comment]
still having problems with the bot missing commands. as well as the script spitting errors if you try to use the extra token.

**Comment by Mid0aria** [comment]
Please add a picture or video about the problem when opening a issue.

**Comment by 420002** [comment]
https://github.com/Mid0aria/owofarmbot/assets/142144696/256edc8d-e92f-45dc-b044-fd22fffedf16

video of problem occurring, also refer too my last issue for problem using extra token

**Comment by Mid0aria** [comment]
FIXED TIMING https://github.com/Mid0aria/owofarmbot/commit/c6aa811e9ae9a30bf39c7ec6528f1ce039fd1939
